### ISSUE TITLE
Вы уже выше нашли позицию ?

### ISSUE THREAD

**Issue by coursar** [NURGALIMOV/http-server#5]
https://github.com/NURGALIMOV/http-server/blob/804b9325a29df261b65b1150e216049528ffe7ea/src/main/java/ru/inurgalimov/http/processor/ControllerBeanPostProcessor.java#L61

**Comment by NURGALIMOV** [comment]
Я так понял тут речь идет о дублировании кода, в рамках другого issue перенес в утилитный класс:
https://github.com/NURGALIMOV/http-server/commit/a712cf0fc8613762f93e1133ee45c0fc708d54e5
